title: Junwon's book
author: Junwon
copyright: "2024"

repository:
  url: https://github.com/junwon1022/delft
  branch: main

execute:
  execute_notebooks: auto

sphinx:
  extra_extensions:
    - sphinx.ext.intersphinx

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - linkify

html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true